name: LineageOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Alanı Temizle ve Arttır
        run: |
          sudo rm -rf /usr/share/dotnet /opt/gh /usr/local/lib/android/sdk
          sudo apt-get clean
          df -h

      - name: Bağımlılıkları Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev libelf-dev libncurses5 libncurses5-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev python3 python-is-python3

      - name: Kaynak Kodları İndir ve Repo Kurulumu
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          
          export PATH=~/bin:$PATH
          
          mkdir lineage && cd lineage
          git config --global user.name "Builder"
          git config --global user.email "builder@action.com"
          repo init -u https://github.com/LineageOS/android.git -b cm-14.1
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

      - name: Tarayıcıdaki Cihaz Ağacını Klonla ve Başlat
        run: |
          export PATH=~/bin:$PATH
          cd lineage
          
          # Doğrudan ekranda gösterdiğin güncel depoyu klonluyoruz
          rm -rf device/samsung/degaswifi
          git clone https://github.com/simionelomu/SM-T230NU-Degaswifi-LineageOS-14.1.git device/samsung/degaswifi
          
          source build/envsetup.sh
          brunch degaswifi
