- name: Test Dosyası Oluştur ve Kaydet
        run: |
          echo "SM-T230 LineageOS Altyapısı Başarıyla Kuruldu!" > sm-t230-bilgi.txt

      - name: Çıktıyı Paketle
        uses: actions/upload-artifact@v4
        with:
          name: sm-t230-cikti
          path: sm-t230-bilgi.txt
